apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trouble-app
  template:
    metadata:
      labels:
        app: trouble-app
    spec:
      containers:
      - name: health-app
        image: piyush540/health:02
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: trouble-config
              key: APP_PORT
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: trouble-secret
              key: API_KEY
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 1
        resources:
          limits:
            memory: "1Gi"
            cpu: "250m"
          requests:
            memory: "640Mi"
            cpu: "100m"
